### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by RossComputerGuy** [syvaidya/openstego#31] opened 2018-11-09 00:50 UTC
```
java.lang.NullPointerException
	at com.openstego.desktop.util.UserPreferences.init(UserPreferences.java:57)
	at com.openstego.desktop.OpenStego.main(OpenStego.java:429)
```
I just installed it

**Comment by MrCode97** [comment] 2018-11-14 13:28
Executing from openstego (not within the /lib folder) worked fine for me:
`java -jar lib/openstego.jar`
or
`java -jar <absolute path>/openstego/lib/openstego.jar`

**Comment by RossComputerGuy** [comment] 2018-11-14 16:03
I'm using the AUR package.

**Comment by syvaidya** [comment] 2018-12-02 12:38
@SpaceboyRoss01 not sure what is AUR package, but looks like that the package is incorrectly built. Can you check if openstego.jar file is there, and if so extract the contents using any zip utility and check if following file exists: com/openstego/desktop/resource/openstego.ini

**Comment by RossComputerGuy** [comment] 2018-12-02 16:03
https://aur.archlinux.org/packages/openstego/ this is what I'm using because I'm using Arch and I don't know where the jar is located

**Comment by RossComputerGuy** [comment] 2018-12-03 04:39
@MrCode97 I don't know where the lib directory for openstego is.

**Comment by RossComputerGuy** [comment] 2018-12-03 04:48
I found out openstego is located at /usr/share/java/openstego/openstego.jar but running it still causes a NullPointerException.02.12.2018, 20:39, "SpaceboyRoss01" <notifications@github.com>:@MrCode97 I don't know where the lib directory for openstego is.

**Comment by syvaidya** [comment] 2018-12-08 10:27
I saw that in that package the openstego.sh is having following line:

`java -jar "/usr/share/java/openstego/openstego.jar" "$@"`

It seems to be okay. Did you try running openstego using "openstego.sh" script?

**Comment by RossComputerGuy** [comment] 2018-12-08 18:42
Yes--Sent from Yandex.Mail for mobile08.12.2018, 02:27, "Samir Vaidya" <notifications@github.com>:I saw that in that package the openstego.sh is having following line:
java -jar "/usr/share/java/openstego/openstego.jar" "$@"
It seems to be okay. Did you try running openstego using "openstego.sh" script?

**Comment by syvaidya** [comment] 2018-12-15 06:51
Can you try downloading zip version directly from github releases, and try that instead of using ArchLinux package?

**Comment by RossComputerGuy** [comment] 2018-12-15 06:53
it does the same thing.

**Comment by syvaidya** [comment] 2018-12-17 05:29
Thanks, I am able to reproduce it. The issue happens only first time you launch OpenStego. It fails with NPE, but it still creates "openstego.ini" file in the user's home folder, and next launch onwards it works fine. I'll fix this with next release.

**Comment by syvaidya** [comment] 2018-12-17 05:37
Fixed in master branch. Will be part of next release.

**Closed as completed by syvaidya** 2018-12-17 05:37 UTC
Labels: bug
