### ISSUE TITLE
-p not working 

### ISSUE THREAD

**Issue by EmilDey** [syvaidya/openstego#49] opened 2022-01-15 21:52 UTC
i have the same problem that the other user. the command to embed and extract with password seems that it is not working. embed with -p  generate a image without password and extract always ask for a password (it doesnt use the given password). to try to debugging i use the gui to generate a image with password and extract with the command line.

**Comment by syvaidya** [comment] 2022-01-16 07:21
Duplicate of #48

**Closed as completed by syvaidya** 2022-01-16 07:21 UTC
